### ISSUE TITLE
Language tags using '-' not supported

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-date-picker-control#6]
The following line causes a problem when using a composite language tag with `-` as component separator:

https://github.com/LaxarJS/ax-date-picker-control/blob/0170c66/ax-date-picker-control.js#L227

This will work for e.g. `en_US`, but not for `en-US`.

Instead, we should lowercase the entire tag and transform `-` to `_`.

**Comment by x1B** [comment]
Still present on `master`:
https://github.com/LaxarJS/ax-date-picker-control/blob/e5d02dd/laxar-date-picker-control.js#L232

**Comment by jpommerening** [comment]
The 1-to-2 upgrade was feature- and bug-complete.

**Comment by x1B** [comment]
👍 just wanted to verify that it's still there :)

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`), `master-1.x` (`v1.1`) and `release-1.0.x` (`v1.0.4`).
